### ISSUE TITLE
C1 - User signup

### ISSUE THREAD

**Issue by t2tato01** [Project-Parcel-Locker-App/front-end#8]
## Task Description

The application must enable the signup of a user. A user is created by entering a username and password, which enables logging into the application.

### Things needs to be done

- [ ] Database design and implementation of related parts
- [ ] API route to creare/signup a new user
- [ ] Storing user information to the database

### Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Code Refactoring
- [ ] Documentation Update
- [ ] Other (Please specify)

## Requirement Number

**Linked Issues**

If this request is related to or duplicates other issues, please link them here.
